# Generated by Django 3.2.6 on 2021-08-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('employees', '0002_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
