# Generated by Django 3.2.6 on 2021-08-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('employees', '0003_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='picture_id',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
